pool:
  vmImage: 'ubuntu-16.04'
steps:
  - script: ls
    workingDirectory: $(agent.homeDirectory)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
      architecture: 'x64'
  - script:  pip install -r requirements.txt
    displayName: 'Install tools'
  - script: python scripts/compute_on_vm.py
    displayName: 'Run build'
    workingDirectory: $(agent.homeDirectory)
